### ISSUE TITLE
Using sg-core as data source results in no nodes in list

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/dashboards#12]
When using sg-core the label containing the nodes is `host`. On legacy Smart Gateway the label is `exported_host`. Need to move the dashboard to using the new label name for nodes.

**Comment by csibbitt** [comment]
https://github.com/infrawatch/dashboards/commit/b1df60060998e2d3a52bb24553a9bc6afcd643f5#diff-b8492f864ad75bfcd2177d9f73df8c17
