### ISSUE TITLE
move json description in dashboard object to grafonnet representation

### ISSUE THREAD

**Issue by pleimer** [infrawatch/dashboards#24]
The Grafana operator supports a [grafonnet](https://grafana.github.io/grafonnet-lib/) representation of the dashboards [1]. This is much cleaner and maintainable than using a json blob. 

[1] https://github.com/integr8ly/grafana-operator/blob/master/documentation/dashboards.md

**Comment by csibbitt** [comment]
Just want to mention that in the past we had briefly considered https://github.com/deliveryhero/grafyaml as well, I think. Definitely onboard with using something that makes it easier to review changes.

**Comment by pleimer** [comment]
@csibbitt will look into that. Grafana operator does not work with grafyaml AFAICT, however STO could do a yaml to json translation
